### ISSUE TITLE
#1 - Review

### ISSUE THREAD

**Issue by NicolayGolovnev** [kpechenenko/task-manager#1]
https://github.com/kpechenenko/task-manager/blob/2ffaf0051b1cee09c4b00066b7d9b2f5626e9f06/src/main/java/ru/kpechenenko/task/manager/entity/Task.java#L31-L36
Вот ты используешь конструктор со всеми параметрами, но при этом еще и юзаешь аннотации от Lombok. Почему бы и конструктор со всеми параметрами не указать аннотацией?

**Comment by NicolayGolovnev** [comment]
[    private static final String TASK_RESOURCE = "/tasks";
    private static final String TAG_RESOURCE = "/tags";](https://github.com/kpechenenko/task-manager/blob/2ffaf0051b1cee09c4b00066b7d9b2f5626e9f06/src/main/java/ru/kpechenenko/task/manager/controller/TaskManagerController.java#L18-L19)

Обычно пути-маппинги конкретных сущностей указывается в единственном числе - .../task/..., .../tag/...

**Comment by kpechenenko** [comment]
Конструктор не со всеми параметрами, а без `id`, поэтому lombok для его генерации не подходит, использую рукописный.

По именованию ресурсов придерживаюсь [совета](https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design#:~:text=collection%20of%20orders%3A-,HTTP,could%20define%20a%20route%20for%20the%20path%20/customers/%7Bid%7D.,-Also%20consider%20the) от микромягких и [совета](https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/#:~:text=3.%20Name%20Collections,posts/123.) от фри код кемпа.
